apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/base-db
  SPRING_DATASOURCE_USERNAME: base
  SPRING_DATASOURCE_PASSWORD: base
  APP_JWT_SECRET: YrRZyvDR72HEn+z+EmjcYdBRY1Nw3uDncT6lLv8HEgkj90p2m8uWTcgXMWPydoMH9VRIj1E29QP4LhgFF59dCw==
  APP_CORS_ALLOWED_ORIGINS: http://192.168.49.2:30080