name: CI

on:
  pull_request:
  push:
    branches: [ "master", "main" ]

jobs:
  backend:
    name: Backend (Spring Boot)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: base-db_ci
          POSTGRES_USER: base
          POSTGRES_PASSWORD: base
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U base -d base-db_ci"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build + tests
        env:
          SPRING_PROFILES_ACTIVE: ci
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/base-db_ci
        run: mvn -B -ntp clean verify

  frontend:
    name: Frontend (Angular)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

  docker:
    name: Build & Push Docker images
    runs-on: ubuntu-latest
    needs: [ backend, frontend ]

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Image backend (ce qui existait déjà)
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: novytris/mondecole-back:latest

      # Image frontend (nouveau)
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: novytris/mondecole-front:latest


  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: [ docker ]
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            docker-compose pull
            docker-compose up -d
